### ISSUE TITLE
Generate a new Go type for each YAML dictionary

### ISSUE THREAD

**Issue by mikeschinkel** [ufukty/gonfique#1]
[Reference from Reddit](https://www.reddit.com/r/golang/comments/1aeu6zz/comment/kom4jm1/?utm_source=reddit&utm_medium=web2x&context=3): 

All the [nesting in the generated output](https://github.com/ufukty/gonfique?tab=readme-ov-file#full-example) makes it really hard to read the code for when trying to work with it after generation.

More importantly it makes passing parts of the YAML to funcs as detached values types impossible without hand-editing your output and adding the other types oneself.

Why not provide an option to generate a new Go type for each dictionary? I could definitely see using it if it were to generate multiple types, but not as is. Either that, or I might have to fork it when I need it, and add that capability.

**Comment by ufukty** [comment]
I am aware that there are couple of problems like reduced readability and losing relevancy between same type of config pieces caused by using inline struct definitions. 

One solution to problem can be the one you mention. We can have different `*ast.TypeSpecs` for components of `type Config` that `gonfique` encountered them twice during the process. So, the final result can change like in below example. 

```go
type Config struct {
  Github struct {
    Domain   string `yaml:"Domain"`
    Gateways struct {
      Public struct {
        Path     string `yaml:"Path"`
        Services struct {
          Document struct {
            Path      string `yaml:"Path"`
            Endpoints struct {
              List struct {
                Method string `yaml:"Method"`
                Path   string `yaml:"Path"`
              } `yaml:"List"`
            } `yaml:"Endpoints"`
          } `yaml:"Document"`
          Objectives struct {
            Path      string `yaml:"Path"`
            Endpoints struct {
              Create struct {
                Method string `yaml:"Method"`
                Path   string `yaml:"Path"`
              } `yaml:"Create"`
            } `yaml:"Endpoints"`
          } `yaml:"Objectives"`
          Tags struct {
            Path      string `yaml:"Path"`
            Endpoints struct {
              Creation struct {
                Path   string `yaml:"Path"`
                Method string `yaml:"Method"`
              } `yaml:"Creation"`
              Assign struct {
                Method string `yaml:"Method"`
                Path   string `yaml:"Path"`
              } `yaml:"Assign"`
            } `yaml:"Endpoints"`
          } `yaml:"Tags"`
        } `yaml:"Services"`
      } `yaml:"Public"`
    } `yaml:"Gateways"`
  } `yaml:"Github"`
  Gitlab struct {
    Domain string `yaml:"Domain"`
  } `yaml:"Gitlab"`
}
```

```go
type A struct {
  Method string `yaml:"Method"`
  Path   string `yaml:"Path"`
}

type Config struct {
  Github struct {
    Domain   string `yaml:"Domain"`
    Gateways struct {
      Public struct {
        Path     string `yaml:"Path"`
        Services struct {
          Document struct {
            Path      string `yaml:"Path"`
            Endpoints struct {
              List A `yaml:"List"`
            } `yaml:"Endpoints"`
          } `yaml:"Document"`
          Objectives struct {
            Path      string `yaml:"Path"`
            Endpoints struct {
              Create A `yaml:"Create"`
            } `yaml:"Endpoints"`
          } `yaml:"Objectives"`
          Tags struct {
            Path      string `yaml:"Path"`
            Endpoints struct {
              Creation struct {
                Path   string `yaml:"Path"`
                Method string `yaml:"Method"`
              } `yaml:"Creation"`
              Assign A `yaml:"Assign"`
            } `yaml:"Endpoints"`
          } `yaml:"Tags"`
        } `yaml:"Services"`
      } `yaml:"Public"`
    } `yaml:"Gateways"`
  } `yaml:"Github"`
  Gitlab struct {
    Domain string `yaml:"Domain"`
  } `yaml:"Gitlab"`
}
```

My first thought is the organizational improvement opportunity is still limited following this way. Because; as we go from the leaves to the nodes above in type tree, there are less commonality observed between node types due to the keys are being (and have to be) different. 

We need more clarity on rules of what makes two pieces (of config.yml) as same type. Especially when involved keys are different. 

Current handling of type defining is not intended to be definitive. A solution attempt is going underway in [substitution branch](https://github.com/ufukty/gonfique/tree/substitution). Although it follows different method. Makes gonfique to accept user provided types for pieces of `config.yml` in a file (`use.go`) like `Endpoints` in example above. 

Maybe the method you mention makes more sense since it requires less work to user. 

Thanks for contribution.

**Comment by ufukty** [comment]
Below might be easier to read, without improving code organization. This just separates inline type definitions that are found in a plural field name (eg. Endpoints, Services, Gateways), without requiring isolated typedefs to share same fieldnames-types (twice-encountered)

```go
type Endpoint struct { // twice-encountered, generalized name
  Method string `yaml:"Method"`
  Path   string `yaml:"Path"`
}

// one of the field's type in a inline type that is given to plural name field
type (
  GithubPublicGatewayDocumentService struct {
    Path      string `yaml:"Path"`
    Endpoints struct {
      List Endpoint `yaml:"List"`
    } `yaml:"Endpoints"`
  }

  GithubPublicGatewayObjectiveService struct {
    Path      string `yaml:"Path"`
    Endpoints struct {
      Create Endpoint `yaml:"Create"`
    } `yaml:"Endpoints"`
  }

  GithubPublicGatewayTagsService struct {
    Path      string `yaml:"Path"`
    Endpoints struct {
      Creation Endpoint `yaml:"Creation"`
      Assign   Endpoint `yaml:"Assign"`
    } `yaml:"Endpoints"`
  }

  GithubPublicGateway struct {
    Path     string `yaml:"Path"`
    Services struct {
      Document   GithubPublicGatewayDocumentService  `yaml:"Document"`
      Objectives GithubPublicGatewayObjectiveService `yaml:"Objectives"`
      Tags       GithubPublicGatewayTagsService      `yaml:"Tags"`
    } `yaml:"Services"`
  }
)

type Config struct {
  Github struct {
    Domain   string `yaml:"Domain"`
    Gateways struct {
      Public GithubPublicGateway `yaml:"Public"`
    } `yaml:"Gateways"`
  } `yaml:"Github"`
  Gitlab struct {
    Domain string `yaml:"Domain"`
  } `yaml:"Gitlab"`
}
```

**Comment by mikeschinkel** [comment]
> _We need more clarity on rules of what makes two pieces (of config.yml) as same type. Especially when involved keys are different._

My concern was not so much for shared items — although as you point one that can be a concern — but instead for making each node independent and without any nesting directly within the `struct` definition itself.  I pretty much always write independent structs when I am working in Go with JSON, and would want to do the same for working with YAML.

> `GithubPublicGatewayDocumentService`
> `GithubPublicGatewayObjectiveService`
> `GithubPublicGatewayTagsService`

Personally, I would not want to use types with type names.  I'd much rather then be shortened to the shortest unique name, e.g.
- `DocumentService`, 
- `ObjectiveService`,
- `TagsService`

In addition, it would be great if I could write a config file that would allow me to do something like this:

```yaml
types:
   - config.github.domain.gateways.public.services.document: DocService
   - config.github.domain.gateways.public.services.objectives: ObjService
   - config.github.domain.gateways.public.services.endpoints: EPService
```

BTW, I am just giving one person's feedback. Just want to make it clear I'm not expecting you to take any of my advice, even if I argue for it.  Take whatever has value to you and decide how you want to move forward. I won't be offended.

**Comment by ufukty** [comment]
I value user feedback to stay relevant for greater user base. I appreciate you mention your expectations on feedback handling. Having contributors like you at this early stage is great for the project. I see this as an opportunity to increasing engagement with community.

I don't consider an option where gonfique asks user a separate yaml file; as they can get out-of-sync to easily. 

Providing users a flag to direct gonfique to always create isolated struct definitions (instead inline definitions) is easy to implement. Although the principle on how to name created types is unclear. More verbose option is having all the key-path in the name to guarantee stability. Thought as you said, long names are not improving eye comfort. Automating type name generation is technically possible. But as the config schema changes, shortest-unique identifier can get altered. Eg. we can not keep naming the `github.domain.gateways.public.services.objectives` as `ObjectiveService` after`Gitlab` gets `gitlab.domain.gateways.public.services.objectives`. 

As we discussed in the other issue #2, it might be possible to assign names based on user preference that is specified in input config file. But I still have concerns on community's response on bloating config files that are written for using with other tools (k8s, ansible, router etc.).

**Comment by mikeschinkel** [comment]
I will make any relevant replies on #2.

**Comment by ufukty** [comment]
After arriving to conclusion on #2 (comments [1](https://github.com/ufukty/gonfique/issues/2#issuecomment-1925452643), [2](https://github.com/ufukty/gonfique/issues/2#issuecomment-1925670074), this issue stays relevant. 

Latest state is providing an option for user such as `--no-inline` to always create named types for field types. This way they can reused/mentioned in other contexts such as input/output parameter list or receiver type. 

Although naming of generated types is open to alternative solutions. There could be automatic name creation or user-provided explicit mapping between yaml keys and Go type names. Or there could be directions in that config file on how to build and where to apply types just as in the example in link.

**Comment by mikeschinkel** [comment]
> _"Although naming of generated types is open to alternative solutions. There could be automatic name creation or user-provided explicit mapping between yaml keys and Go type names. Or there could be directions in that config file on how to build and where to apply types just as in the example in link."_

Or both, ideally.

I added Issue #5 for the latter.

**Comment by ufukty** [comment]
The latest addition to gonfique, `-organize` flag directs the tool to generate separate, named type specifications for each struct-type-field whether or not it is twice-encountered. [Output example](https://github.com/ufukty/gonfique/blob/main/examples/k8s-organize-and-use/output.go)

It does not directly targets this issue since the generated type names are marked private. This is because it can not be guaranteed that each type will get the same name after config changes and gonfique rerun.

I am still thinking about feasibility of explicit, user-provided mappings. But #5 is more relevant to that discussion.

Is this issue has something left that `-organize`, `-use` or #5 doesn't address?

**Comment by mikeschinkel** [comment]
Hmm. 

While I understand the motivation to make the types private in that output example, it really defeats the point of making then separate structs.  If they cannot be used directly as public, making then separate is really a moot exercice, or at least from my perspective and envisioned use-cases.

Said more explicitly, if it is too hard to generate public types I would just close this ticket as _"won't fix."_

#jmtcw #fwiw

**Comment by ufukty** [comment]
Users can use `-organize` flag to direct gonfique to define (automatically) named types and re-use those types multiple times wherever types match. Organizing produces a more hierarchically structured type definition, increasing code-reuse. One note, produced types will get automatically named to avoid creating chores for dev at start. (Product type names are not exported, so, they can't be referenced from outside package)

To direct gonfique to create type names that can be referenced from outside package; developers are expected to provide a mapping file which its details and syntax are explained in docs/mapping.md file. It provides highly flexible means to define rules that will stay relevant against changing schemas through wild-card support. 

Thanks for your contribution and time.
